### ISSUE TITLE
arcpy.GetInstallInfo() does not have key LicenseLevel in ArcMap

### ISSUE THREAD

**Issue by katja-ng911** [NENA911/NG911GISDataModel#27]
To check license level, the script calls for LicenseLevel key of GetInstallInfo object:

 if install_info['LicenseLevel'] == "Basic":
        # https://pro.arcgis.com/en/pro-app/latest/arcpy/functions/adderror.htm
        arcpy.AddError('This script requires an ArcGIS Desktop licensing level '
                       'of "Standard" or "Advanced".')
        exit()

This key does not exist in ArcMap, only Pro:
ArcMap: https://desktop.arcgis.com/en/arcmap/latest/analyze/arcpy-functions/getinstallinfo.htm
ArcGIS Pro:  https://pro.arcgis.com/en/pro-app/latest/arcpy/functions/getinstallinfo.htm

This results in the following error when running the script (in ArcMap/Catalog or directly in IDLE):

Traceback (most recent call last):
  File "E:\NENA\NG911DataModel_v2\NENA_NG911_Scripts\create_ng911_fgdb.py", line 315, in <module>
    main(**script_params)
  File "E:\NENA\NG911DataModel_v2\NENA_NG911_Scripts\create_ng911_fgdb.py", line 48, in main
    if install_info['LicenseLevel'] == "Basic":
KeyError: 'LicenseLevel'

Here's the way to access license info/level in ArcMap: https://desktop.arcgis.com/en/arcmap/latest/analyze/arcpy-functions/checkproduct.htm

**Comment by dds-development** [comment]
Thanks for that catch. 

The objective of the code block below is to capture the ArcGIS Desktop 10.x check first and then check ArcGIS Pro second. Unfortunately, I only have an Advanced license of ArcGIS Desktop 10.x. 

If you change the code block as below, does this resolve the issue? 

```
    # Check the license level is not "Basic" as the CreateRelationshipClass
    # function requires a "Standard or "Advanced" license
    if install_info['Version'].startswith('10.'):
        if arcpy.ProductInfo() == 'ArcView':
            arcpy.AddError('This script requires an ArcGIS Desktop licensing level '
                       'of "Standard" or "Advanced".')
            exit()
    elif install_info['LicenseLevel'] == "Basic":
        arcpy.AddError('This script requires an ArcGIS Desktop licensing level '
                       'of "Standard" or "Advanced".')
        exit()
```
to
```
    # Check the license level is not "Basic" as the CreateRelationshipClass
    # function requires a "Standard or "Advanced" license
    if install_info['Version'].startswith('10.'):
        if arcpy.ProductInfo() == 'ArcView':
            arcpy.AddError('This script requires an ArcGIS Desktop licensing level '
                       'of "Standard" or "Advanced".')
            exit()
    else:
        if install_info['LicenseLevel'] == "Basic":
            arcpy.AddError('This script requires an ArcGIS Desktop licensing level '
                           'of "Standard" or "Advanced".')
            exit()
```

**Comment by tomneer** [comment]
Thanks for that catch. (replying with correct account)...

The objective of the code block below is to capture the ArcGIS Desktop 10.x check first and then check ArcGIS Pro second. Unfortunately, I only have an Advanced license of ArcGIS Desktop 10.x. 

If you change the code block as below, does this resolve the issue? 

```
    # Check the license level is not "Basic" as the CreateRelationshipClass
    # function requires a "Standard or "Advanced" license
    if install_info['Version'].startswith('10.'):
        if arcpy.ProductInfo() == 'ArcView':
            arcpy.AddError('This script requires an ArcGIS Desktop licensing level '
                       'of "Standard" or "Advanced".')
            exit()
    elif install_info['LicenseLevel'] == "Basic":
        arcpy.AddError('This script requires an ArcGIS Desktop licensing level '
                       'of "Standard" or "Advanced".')
        exit()
```
to
```
    # Check the license level is not "Basic" as the CreateRelationshipClass
    # function requires a "Standard or "Advanced" license
    if install_info['Version'].startswith('10.'):
        if arcpy.ProductInfo() == 'ArcView':
            arcpy.AddError('This script requires an ArcGIS Desktop licensing level '
                       'of "Standard" or "Advanced".')
            exit()
    else:
        if install_info['LicenseLevel'] == "Basic":
            arcpy.AddError('This script requires an ArcGIS Desktop licensing level '
                           'of "Standard" or "Advanced".')
            exit()
```

**Comment by katja-ng911** [comment]
I don't have access to Basic either but I added an else statement to print the version if it's not ArcView and it told me, correctly, that I have ArcInfo and proceeded along (currently running but past the license check). Good to go.

**Comment by tomneer** [comment]
Thanks again. Code change committed. If you run into anything else, please let us know.
