### ISSUE TITLE
Add progress messages when script is run in an IDE

### ISSUE THREAD

**Issue by katja-ng911** [NENA911/NG911GISDataModel#28]
The Create NG9-1-1 File Geodatabase script outputs tons of useful progress messages when run in an ArcGIS application. It does not output anything when run via a Python IDE.

Since the script is intended to run via either (i.e., it includes local_params for running in an IDE), it would be useful to print the same messages to console as are added to the Geoprocessing progress window. Otherwise, it just looks like it's hanging for 10 minutes until it returns.

Perhaps create a function that would do both arcpy.AddMessage/arcpy.AddWarning/arcpy.AddError and a print statement of the same message.

```
def addMsg(message):
    arcpy.AddMessage(message)
    print(message)
def addWarn(message):
    arcpy.AddWarning(message)
    print(message)
def addErr(message):
    arcpy.AddError(message)
    print(message)
```
This is is an enhancement request, not a bug report, but it would greatly improve the user experience (and make troubleshooting easier).

**Comment by tomneer** [comment]
The Python script was initially developed to run solely through ArcGIS Toolbox and only recently changed to run from an IDE. Would you see any benefit to also creating a log file, in addition to the print()?

For example using [logging](https://docs.python.org/3/library/logging.html) like this:

```python
def log(level, msg, logger):
	logger(level, msg)
	if level == 'WARN':
		arcpy.AddWarning(msg)
	elif level in ('ERROR', 'CRITICAL':
		arcpy.AddError(msg)
	else:
		arcpy.AddMessage(msg)
```

**Comment by katja-ng911** [comment]
Yes, I think logging would be useful. I'd like to see the output in the console, not just a logfile. That way I could watch progress in the console AND have a log of the run as a file (if this is how you choose to implement it).

**Comment by tomneer** [comment]
The Python logging module provides both logging to file and console.

The script is very chatty since our tests generally show it takes about 8-9 minutes to run through the entire script. We will definitely consider this as an enhancement to discuss with the Working Group.

**Comment by tomneer** [comment]
Enhanced logging has been added including the creation of log files.
