### ISSUE TITLE
Minor enhancement idea for the create_ng911_fgdb.py file: Include try/except for 'import arcpy' line

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#29]
**Is your feature request related to a problem? Please describe.**

Yes, this would be a potential problem for ArcGIS Pro users with Python 3.x. This is something I've noticed at our agency with standalone Python 3.x scripts - there are a couple of scenarios where a standalone script will fail and immediately crash on the "import arcpy" line if the user is not signed in to Pro or isn't utilizing an offline Pro license. Additionally, if a user loses internet access to their Pro licensing through ArcGIS Online or Portal, it could trigger this failure as well. Many of our end-users don't need to have ArcGIS Pro open to run automated workflows, so they may not realize they aren't signed in to ArcGIS Pro.

When the failure is triggered, a RuntimeError will occur on the import arcpy line with a error message stating "The Product License has not been initialized."

**Describe the solution you'd like**

If a user is running this script through the .tbx file, it's a non-issue (because they'll already have ArcGIS Pro open and must sign in). However, if the user is trying to run this as a standalone script with ArcGIS Pro's flavor of Python 3.x, then adding a try/except around the import arcpy statement has proven helpful (for our group at least) and will catch these scenarios for alerting the end-user. By creating a custom error pop-up for them, it acts as a reminder for them to check their sign-in or network connection.

Below is an example of what I've used in many standalone scripts at our agency:

```
# ArcPy module is imported at this location so as to check for any runtime
# errors (due to internet connectivity issues and/or licensing issues).
try:

    import arcpy

except RuntimeError:  # Example: "The Product License has not been initialized."

    # If unable to import arcpy module, display a pop-up window with error message.
    import tkinter
    from tkinter import messagebox

    # Creates pop-up window as root.
    # This is required to launch messagebox windows.
    root = tkinter.Tk()

    # Hides the root window (since we are opening a separate messagebox,
    # the root window is blank and unnecessary to see).
    root.withdraw()

    # In the event of a "Runtime Error", the user is given an error message.
    messagebox.showerror("ArcPy Error Message", "ERROR: Unable to verify ArcGIS licensing.\n"
                                                "This could be the result of not being signed in to ArcGIS Pro\n"
                                                "or you're experiencing internet connectivity issues.\n"
                                                "Unable to proceed.")

    # Exit the application.
    exit()
```

**Describe alternatives you've considered**

N/A

**Additional context**

If you need to test this for yourself, just make sure you are signed out of ArcGIS Pro before executing the script as a standalone.

**Comment by tomneer** [comment]
Ahhh... [160485: The Product License has not been initialized](https://pro.arcgis.com/en/pro-app/latest/tool-reference/tool-errors-and-warnings/160001-170000/tool-errors-and-warnings-160476-160500-160485.htm). Typically run across this when service accounts have not been authorized and typically provide the following text.

---

### Authorizing ArcGIS Pro 
When using the ArcPy libraries, the service account MUST be authorized. The following steps will configure ArcGIS Pro 
operate.

1. Right-click on **ArcGIS Pro** from the **Start** menu and select **More** > **Run as different user**.
2. Login in with the service account credentials
3. In the sign-in windows, click the configure license settings
4. Sign into Portal or ArcGIS Online.

---

Interesting approach using a `try/except` for an entire script. Definitely worth discussing with the working group especially with the Esri presence.

**Comment by tomneer** [comment]
@katja-ng911 - How does Esri typically handle this in their geoprocessing tools?

**Comment by tomneer** [comment]
Thank you both for reporting this. Sounds like something to add with the enhanced logging capabilities.

**Comment by tomneer** [comment]
Per Work Group discussion [2022-12-21], this will be added as documentation into the **Known Issues**
