### ISSUE TITLE
The "Create NG9-1-1 File Geodatabase" script is missing from .tbx within ArcMap 10.8.1

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#30]
**Describe the bug**
I've been familiarizing myself with the .tbx scripts this afternoon. The ArcGIS Pro script for creating an Esri File GDB is working in Pro 3.0.2 as expected, but I am unable to access the .tbx script needed for execution within ArcMap 10.8.1. The .tbx shows up, but it's empty.

I know the documentation mentions "Note: This has been only testing in ArcGIS Desktop 10.8.1 and ArcGIS Pro v2.9.x and 3.0.x. We are aware of issues with ArcGIS Desktop 10.5.x where the Create NG911 FGDB tool does not display in the ArcGIS Toolbox." However, it appears I'm seeing the same behavior in 10.8.1 (using Standard license level). 

My view from ArcGIS Pro 3.0.2 (both scripts appear as expected):
![image](https://user-images.githubusercontent.com/58236078/203168437-4d83d72f-05ab-420d-acdd-b1bd830099f5.png)

My view from ArcMap 10.8.1 (toolbox displays, but it's empty):
![image](https://user-images.githubusercontent.com/58236078/203168590-d829cb20-e322-4599-9625-f0845f2f2043.png)

Is anybody else seeing this, or is there something obvious I'm missing? It's been awhile since I've tinkered with Esri's Python toolboxes in ArcMap, so feel free to blame it on user-error if needed.

**To Reproduce**
Forked the repository, followed steps within GitHub read me file for ArcMap (import toolbox, expand toolbox, open script), but was unable to expand the toolbox to show a script within. Also, tried the same approach with the .zip file containing the .tbx (in case I manipulated something within my fork accidentally). Both gave same behavior.

**Comment by tomneer** [comment]
We were trying to maintain a single ArcGIS Toolbox to support both ArcGIS Pro and ArcMap. Unfortunately, this isn't the first time that ArcGIS Pro caused problems for ArcMap. We have separated the Toolboxes into an ArcGIS Pro and ArcMap version to prevent this issue in the future.

Please let us know if this works better. Thank you for the feedback!

**Comment by tomneer** [comment]
It's is the default string I put into the spatial reference. I copied from Pro but it must be a different definition in ArcMap

Would you select WGS84 from the selector and try again?

Thanks
Tom

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by jasonhorning** [comment]
Re-selected GCS_WGS_1984, same behavior.  Do the scripts need to be placed somewhere specific?  I just downloaded the tool to Downloads and added it to ArcToolbox from there.

**Comment by tomneer** [comment]
You can double-check the path to the script by right-clicking and verifying in the Properties. I am pretty sure I checked "use relative paths" but now not sure.

**Comment by NCT911-DLindsey** [comment]
Jason, I was getting same behavior as you. Tom, it looks like this might be the issue:

Script path shows "create_n911_fgdb.py" instead of "create_ng911_fgdb.py"  When I remapped to the non-typo'd file, it worked.
![image](https://user-images.githubusercontent.com/58236078/203358134-6262002f-a512-4757-8275-dfb263cff761.png)

Well...it started anyway. Made it to the Creating Domain step, then crashed with 999999.
![image](https://user-images.githubusercontent.com/58236078/203358581-87783b47-f0b1-4b73-84c3-9a3a9e660350.png)

**Comment by tomneer** [comment]
Pushed a new version with the Spatial Reference and Python path fixed. Ran on my version of 10.8.1 and it succeeded. 

Please try with the latest version of [NENA_NG911_Toolbox.zip](https://github.com/NENA911/NG911GISDataModel/blob/main/esri_geodatabase/NENA_NG911_Toolbox.zip).

Let's see if that resolves it or if we get the wonderful 9s error...

**Comment by jasonhorning** [comment]
That fixed it for me in ArcMap 10.5.1.  It pulls up the tool and executes to completion without errors or warnings.

**Comment by NCT911-DLindsey** [comment]
ArcMap .tbx test for me in 10.8.1 was successful, no issues or failures observed at first glance during that run. Nice work, Tom!

**Comment by tomneer** [comment]
Thank you both for all the feedback and testing!
