### ISSUE TITLE
ArcGIS Pro Script - Editor Tracking Issue

### ISSUE THREAD

**Issue by geofinne** [NENA911/NG911GISDataModel#31]
**Describe the bug**
The ArcGIS Pro script throws an error when it gets to the step where it tries to enable date tracking on the DateUpdate field for the Road Centerline feature class.  See attached screenshot and full error report (copied into a .txt).

[ArcGIS_Pro_Script_Error_11292022.txt](https://github.com/NENA911/NG911GISDataModel/files/10118770/ArcGIS_Pro_Script_Error_11292022.txt)
![ArcGIS_Pro_Script_Error_11292022_Screenshot](https://user-images.githubusercontent.com/11874166/204690967-d5ff05df-decc-4869-a653-e4821bd28494.JPG)

**To Reproduce**
1. Run the 'Create NG9-1-1 File Geodatabase' script in the 'NENA_NG911_Toolbox_for_ArcGIS_Pro' toolbox., using ArcGIS Pro (Advanced) v.2.9.0.
2. See error

**Expected behavior**
For the tool to run to completion and create the full file geodatabase.

**Screenshots**
(see description)

**Additional context**
ArcGIS Pro (Advanced) v.2.9.0 was used for this test.

**Comment by geofinne** [comment]
@tomneer , @jasonhorning , not sure if you get notified about an issue without being tagged, so I'm tagging you here.  Thanks!

**Comment by tomneer** [comment]
Sarah,

Thank you for the test. We will attempt to recreate this morning. 

I use ArcGIS Pro 2.9.5 due a bug with a .Net patch that crashes ArcGIS Pro. Not sure I can test 2.9.0 but will try.

Tom

**Comment by tomneer** [comment]
Sarah,

I tested the scripts, this morning, in both ArcGIS Pro 2.9.5 and 3.0.3 and they ran successfully using both "CURRENT" and "10.0" geodatabases. These have also been tested previously in ArcGIS Desktop 10.8.1 and 10.5.1.

To confirm, are you running the scripts from zip archive downloadable at https://github.com/NENA911/NG911GISDataModel/blob/main/esri_geodatabase/NENA_NG911_Toolbox.zip? 

If so, please try again. If the same error occurs, please attempt on a different system/version of ArcGIS Pro. It may have just been a quirk or something specific to ArcGIS Pro 2.9.0.

**Comment by geofinne** [comment]
@tomneer , correct, I'm using the script from that zip archive.  I've tried 3 times with ArcGIS Pro 2.9.0, using the "CURRENT" .gdb.  I'll try another time with "10.0", and then will go ahead and upgrade my Pro to 3.0.3 and will try that.  Just wanted to document that there might be an issue with  Pro 2.9.0.  Thanks!

**Comment by geofinne** [comment]
Hi @tomneer , a quick testing update.  Trying "10.0" for the GDB Version option using Pro 2.9.0 didn't work.  I upgraded to Pro 3.0.3 (and downloaded the new .NET it needed), and the script works fine now!  So, maybe update the documentation about what versions of Pro this works for, then this issue can be closed?  

Thank you!

**Comment by tomneer** [comment]
Sarah,

Thank you for the verification. I think the best course of action is to add a "Known Issues" to the Esri documentation. Once we add that, we will not this Issue as closed.

**Comment by tomneer** [comment]
A **Known Issues** section has been added citing the version-specific issue and recommended solution is to upgrade to ArcGIS Pro 2.9.5 or later.
