### ISSUE TITLE
Add metadata to FGDB template

### ISSUE THREAD

**Issue by geofinne** [NENA911/NG911GISDataModel#32]
**Is your feature request related to a problem? Please describe.**
The file geodatabase template does not have metadata associated with it.

**Describe the solution you'd like**
Create and add appropriate metadata, referencing the version of the data model and associated NENA documentation.

**Describe alternatives you've considered**
n/a

**Additional context**
Screenshot of current metadata (blank): 
![image](https://user-images.githubusercontent.com/11874166/204827022-391ed964-35d6-4dd7-a2cc-27e0de437e26.png)

**Comment by tomneer** [comment]
This is a discussion topic for today's Working Group meeting and was not initially included.

**Comment by geofinne** [comment]
@tomneer , thank you!  I just saw where a new working group for this was recommended, but I think maybe we can start with something basic so it's not completely blank when we publish it.

**Comment by jasonhorning** [comment]
Metadata was added [here](https://github.com/NENA911/NG911GISDataModel).  Not sure how to script in the attachment of metadata to the FGDB itself but we can discuss whether that's necessary or if the loose file is enough.

**Comment by tomneer** [comment]
The v1 metadata file is at https://github.com/NENA911/NG911GISDataModel/blob/main/esri_geodatabase/.archive/v1/NG911_GIS_Metadata.xml

I have some code buried somewhere that uses a metadata XML template to apply to features using ArcPy. It is definitely doable.

**Comment by geofinne** [comment]
Per workgroup call (12/14/2022), leave metadata.xml and add in .gdb-level metadata into the actual geodatabase.  Workgroup to discuss content on the next call, but we should be able to copy the existing metadata and update the references to v2 of the data model standard.

**Comment by jasonhorning** [comment]
I believe the references to the proper standard (v2) were updated in the version here but please verify.

**Comment by tomneer** [comment]
This is a bit more complicated as expected. There are significant changes in the application of metadata between 10x and Pro. Looking into how best to implement this in a script that affects multiple versions.
