### ISSUE TITLE
Mismatching Field Width: Line 1036 of schema_fgdb_v2.py

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#34]
Hey Tom and Jason,

My spam continues...

Regarding line 1036 in the schema_fgdb_v2.py file:
https://github.com/NENA911/NG911GISDataModel/blob/986686da9ae68cdcadf9766cd5943f93969fbbf9/esri_geodatabase/NENA_NG911_Scripts/schema/schema_fgdb_v2.py#L1036-L1037

In the GIS Data Model, the field width for St_PreDir field is capped at 9 characters, but the schema template on line 1036 reflects 10 characters:
![image](https://user-images.githubusercontent.com/58236078/206036775-db26521c-0f7e-4084-9f5d-3543291b8483.png)

-- David L.

**Comment by dds-development** [comment]
This is an error in NENA-STA-006.2-2022, the French directionals include lengths that are 10-characters long. It will be addressed in NENA-STA-006.2.0.a-2022.

**Comment by tomneer** [comment]
This is an error in NENA-STA-006.2-2022, the French directionals include lengths that are 10-characters long. It will be addressed in NENA-STA-006.2.0.a-2022.
