### ISSUE TITLE
Mismatching Field Width (St_PosDir): Line 1046 of schema_fgdb_v2.py

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#35]
Another field width mismatch between GIS Data Model and schema_fgdb_v2.py template, at line 1046 for St_PosDir:

https://github.com/NENA911/NG911GISDataModel/blob/986686da9ae68cdcadf9766cd5943f93969fbbf9/esri_geodatabase/NENA_NG911_Scripts/schema/schema_fgdb_v2.py#L1046-L1047

GIS Data Model also shows a cap of 9 characters for this one, while the script template shows 10 character limit:
![image](https://user-images.githubusercontent.com/58236078/206038591-a1157fbb-c760-4c66-8c56-fe48713f2c49.png)

-- David L.

**Comment by tomneer** [comment]
This is an error in NENA-STA-006.2-2022, the French directionals include lengths that are 10-characters long. It will be addressed in NENA-STA-006.2.0.a-2022.
