### ISSUE TITLE
Mismatching Field Width (RoadClass): Line 1102 of schema_fgdb_v2.py

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#36]
Mismatching field width for **RoadClass** in schema_fgdb_v2.py script (line 1102).

GIS Data Model shows field width capped at 15 characters, but the schema template shows 24 characters.
https://github.com/NENA911/NG911GISDataModel/blob/986686da9ae68cdcadf9766cd5943f93969fbbf9/esri_geodatabase/NENA_NG911_Scripts/schema/schema_fgdb_v2.py#L1102-L1103

![image](https://user-images.githubusercontent.com/58236078/206041708-bf2fef35-8dff-4311-bef4-e79577cbc2b0.png)

-- David L.

**Comment by tomneer** [comment]
This is an error in NENA-STA-006.2-2022, the Road Class domain include lengths that are 24-characters long. It will be addressed in NENA-STA-006.2.0.a-2022.
