### ISSUE TITLE
Field Precision (SpeedLimit): Line 1106 of schema_fgdb_v2.py

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#37]
Here's another field precision issue I wanted to double check with you guys on. 

Regarding line 1106 for the SpeedLimit field:

https://github.com/NENA911/NG911GISDataModel/blob/986686da9ae68cdcadf9766cd5943f93969fbbf9/esri_geodatabase/NENA_NG911_Scripts/schema/schema_fgdb_v2.py#L1106-L1107

The GIS Data Model shows that this field should have a field width (precision) of 3, but the template does not have a limit set in the Index 2 position.
![image](https://user-images.githubusercontent.com/58236078/206042941-134a7c78-55e9-4438-ae43-f751434a5e3e.png)

-- David L.

**Comment by tomneer** [comment]
As per #33, Integer field precision is handled through domains (FGDB) and constraints (PostGIS).

**Comment by jasonhorning** [comment]
In Arcmap 10.5.1, this doesn't seem to be restricted even though a range domain is assigned.   Suggests an Esri issue should be reported or that a check against a newer version of ArcMap is needed.

**Comment by tomneer** [comment]
This issue has been noted in the new **Known Issues** section.
