### ISSUE TITLE
LandmarkNameCompleteAliasTable Issue

### ISSUE THREAD

**Issue by geofinne** [NENA911/NG911GISDataModel#39]
**Description**

In the PostgreSQL script for LandmarkNameCompleteAliasTable, the “SSAP_NGUID” field is not required and the standard calls for the field to be required.

**Comment by tomneer** [comment]
Interesting... The `SSAP_NGUID` is not required in the CellSectorPoint layer and conditional in the LandmarkNamePartTable. This seems to be a documentation inconsistency. Let's discuss at the next working group call. @jasonhorning - Please add this to our list of discussion topics.

**Comment by jasonhorning** [comment]
Added to the data template v2 tasks spreadsheet.

**Comment by tomneer** [comment]
Per the Data Model Template WG call (2022-12-14), this issue will be fixed in the PostgreSQL template and add a note to both templates that the LandmarkName tables will be deprecated when CLDXF v2 is published.

**Comment by jasonhorning** [comment]
I show this issue has having had discussion in our data_template_V2_tasks.xlsx and that completion status is COMPLETE on both the FGDB and PostgreSQL templates.  Can we close?

**Comment by tomneer** [comment]
Need to add the comments to the template about the removal of the LandmarkName tables

**Comment by tomneer** [comment]
Documentation was updated to reflect that the LandmarkNameCompleteAliasTable and LandmarkNamePartTable will be removed.
