### ISSUE TITLE
PostgreSQL: RoadCenterline schema - Line 436 - St_Name Question

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#41]
Hey Tom,

I'm reviewing the PostgreSQL schema for RoadCenterline section, and have a question about Line 436.

St_Name is shown as **St_Name VARCHAR(254)**

https://github.com/NENA911/NG911GISDataModel/blob/986686da9ae68cdcadf9766cd5943f93969fbbf9/postgresql/postgresql_data_model_schema_template.md?plain=1#L436

For other required fields, you have NOT NULL following that, but this required field does not. Is that intentional? Thanks

-- David L.

**Comment by tomneer** [comment]
Verified. This field should be NOT NULL. Thanks David!
