### ISSUE TITLE
PostgreSQL - RoadCenterline template - PostCode and PostComm Ordering

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#42]
Tom,

I'm not sure how relevant this is, but I did notice that PostCode and PostComm were flip-flopped in the code compared to the GIS Data Model. The GIS Data Model shows PostCode_L, PostCode_R, PostComm_L, PostComm_R. The PostgreSQL script shows PostComm_L, PostComm_R, PostCode_L, PostCode_R.

![image](https://user-images.githubusercontent.com/58236078/206776514-a73d4ae8-517b-42c3-bf71-87d09bf63ecb.png)

https://github.com/NENA911/NG911GISDataModel/blob/986686da9ae68cdcadf9766cd5943f93969fbbf9/postgresql/postgresql_data_model_schema_template.md?plain=1#L462-L465

-- David L.

**Comment by tomneer** [comment]
Will flip for consistency. Thanks!
