### ISSUE TITLE
Road Centerline Field Lengths

### ISSUE THREAD

**Issue by JLevandowski** [NENA911/NG911GISDataModel#45]
The lengths of 3 fields within the model are longer than what the Standard suggests....  Street Name Pre Directional, Street Name Post Directional, and Road Class.  Obviously it would be a problem if the model lengths were shorter so this might not really be an issue.

Thanks

**Comment by tomneer** [comment]
Thank you. These are addressed in Issues #22 and #23, which will be referred back to the NENA GIS Data Model Working Group to be corrected in NENA-STA-006.2(a) early next year.
