### ISSUE TITLE
Site Structure Address Points

### ISSUE THREAD

**Issue by dawnblanchard-DOIT** [NENA911/NG911GISDataModel#48]
The data model standard lists the Elevation field (in SiteStructureAddressPoints) as a width of 6, however the geodatabase uses a short integer field type that can only store up to a length of 5. Should we switch this to a long integer?.

**Comment by geofinne** [comment]
Hi @dawnblanchard-DOIT , this is duplicated from the issue I reported.  @tomneer , this one can be closed.

**Comment by tomneer** [comment]
Duplicate of #46, closing as duplicate
