### ISSUE TITLE
StateOrEquivalentA1 Domain

### ISSUE THREAD

**Issue by dawnblanchard-DOIT** [NENA911/NG911GISDataModel#49]
The “StateOrEquivalentA1” domain does not include Canadian or Mexican A1 values. I can provide them if necessary.

**Comment by jasonhorning** [comment]
I think it makes sense to bring it up on the call but I'm inclined to add them and believe this is really just an oversight.  I don't know how useful the template would be in Canada or Mexico if users were domain restricted to just US-based A1 values.  If the MX or CA country values are in the domain listing then it should be implied that the A1s are also included.

**Comment by tomneer** [comment]
Per Working Group discussion [2022-12-21], the Canadian A1s will be included based on https://en.wikipedia.org/wiki/ISO_3166-2:CA, however, the Mexico equivalents at https://en.wikipedia.org/wiki/ISO_3166-2:MX will not be included as Mexico uses three characters which requires modification of the NENA GIS Standard.

**Comment by tomneer** [comment]
The StateOrEquivalentA1 domain has been updated with the Canadian equivalents.
