### ISSUE TITLE
 CellSectorPoint Layer

### ISSUE THREAD

**Issue by dawnblanchard-DOIT** [NENA911/NG911GISDataModel#50]
CellSectorPoint Layer was missing.

**Comment by tomneer** [comment]
The CellSectorPoint layer is available in both versions. I believe it was missing early on in the geodatabase version. I did however notice that the "out_alias" has "Point" duplicated which needs to be corrected.

**Comment by jasonhorning** [comment]
Yes, it was missing and has been added in.  It may be that the zip package does not include it yet so I'll make it a point to update that.

**Comment by jasonhorning** [comment]
Fixed the Point Point issues in out_alias for CellSectorPoint.
