### ISSUE TITLE
Missing PlaceType Domain Values

### ISSUE THREAD

**Issue by geofinne** [NENA911/NG911GISDataModel#51]
Several values are missing from the PlaceType domain (in both the FGDB and Postgres). Values that are missing are highlighted in yellow in the attached registry list: 

[MissingDomainValues_location-type-registry-1.xlsx](https://github.com/NENA911/NG911GISDataModel/files/10229644/MissingDomainValues_location-type-registry-1.xlsx)

**Comment by tomneer** [comment]
The missing values are all vehicle types, not places. The current list is based on the v1 Template. We believe this should be referred back to the GIS Data Model WG for clarification.

**Comment by geofinne** [comment]
Yeah, I noticed that and it's confusing since the standard doesn't say to filter those out.  It just says to use that list as the domain.

**Comment by jasonhorning** [comment]
We made a conscious decision to not add moving object type domains to the domain since none of our features are moving.  If you feel this should be discussed on our next call, we can certainly talk about it.  Good catch by the way!  You're really doing some detailed work!  Thank you!

**Comment by tomneer** [comment]
Per Working Group discussion [2022-12-21], the working group voted to exclude the moving vehicles from the [Location Types Registry](https://www.iana.org/assignments/location-type-registry/location-type-registry.xml) but add documentation as to why they were excluded.

The vehicle location types were excluded as it is usual to address a location that moves but rather address the space the vehicle may occupy.

**Comment by tomneer** [comment]
Documentation was added per WG discussion
