### ISSUE TITLE
Missing StreetNameType Domain Value (FGDB)

### ISSUE THREAD

**Issue by geofinne** [NENA911/NG911GISDataModel#52]
The StreetNameType domain in the File Geodatabase is missing the following value: 

Runne

As seen in the attached registry list: 
[NENA_Registry_StreetNamePreTypesAndStreetNamePostTypes.xlsx](https://github.com/NENA911/NG911GISDataModel/files/10229930/NENA_Registry_StreetNamePreTypesAndStreetNamePostTypes.xlsx)

**Comment by tomneer** [comment]
Confirmed missing in the esri schema (https://github.com/NENA911/NG911GISDataModel/blob/main/esri_geodatabase/NENA_NG911_Scripts/schema/schema_fgdb_v2.py). It is present in the PostgreSQL template

**Comment by jasonhorning** [comment]
Added missing domain value.
