### ISSUE TITLE
nena.State I believe should be nena.StateorEquivalentA1

### ISSUE THREAD

**Issue by rjhale1971** [NENA911/NG911GISDataModel#55]
**Describe the bug**
I've just started testing this all out with the hope of running this with QGIS. If I run the (postgresql) initial Data Model Template SQL Script it's erroring out on line 330. Line 330 references nena.State and from what I can tell I think it should be nena.StateOrEquivalentA1. It's also erroring out on nena.county which I believe should be nena.CountyorEquivalentA2 (line 332)

**To Reproduce**
1. Copy the Data Model Template SQL Script 
2. Copy into PGADMIN
3. Run
4. See Error in the Messages Window: ERROR:  relation "nena.state" does not exist

**Expected behavior**
Completes and creates the intial database. I went through and "fixed" the intial script and it works on my end now. I can submit a pull request if you'd like. 

**Screenshots**

![Screenshot from 2022-12-21 21-18-24](https://user-images.githubusercontent.com/108346131/209040742-86dd24bd-a085-449f-ba0e-647ca5dfe212.png)

**Additional context**
So I'm running TN's 911 standard in QGIS/PostGIS - I had originally starting building my own scripts and stumbled into this and I'm deleting what I've done for this. I'd be more than happy to help test the FOSS4G side of this.

**Comment by tomneer** [comment]
Thank you. This is resolved and I also corrected the same issue with "County" and "CountyOrEquivalentA2"

**Comment by rjhale1971** [comment]
Awesome - Thank ya'll for putting this up. This makes my life a lot easier. Yell if I can do anything else to help.

**Comment by tomneer** [comment]
@rjhale1971 - Thank you for the feedback and bug catches. We are excited to offer these scripts and templates in this format to assist organizations with the transfer and implementation of NG9-1-1 GIS Data Model.
