### ISSUE TITLE
Colons in NG9-1-1 Data Model PostGIS Initial Data Script

### ISSUE THREAD

**Issue by rjhale1971** [NENA911/NG911GISDataModel#56]
**Describe the bug**
There are two colons in the NG9-1-1 Data Model PostGIS Initial Data Script - one at line 639, and one at 640

**To Reproduce**
1. Copy the Data Model Initial Data Script
2.Run
3. It will error out at line 639 (and again at 640 if you fix 639)
4. Error Produced will be:
ERROR:  syntax error at or near ":"
LINE 639: ,  ('urn:service:sos.police.municipal': 'A police force that...

**Expected behavior**
Run to Completion 

**Screenshots**
![Screenshot from 2022-12-22 09-52-33](https://user-images.githubusercontent.com/108346131/209160672-39750560-819a-4808-ad61-1c6a4d5c02fe.png)

**Additional context**
No other problem. I replaced the two colons with commas and it ran. Now to hook up QGIS and build some menus for data input. I can submit a fix if you want - no worries there.

**Comment by tomneer** [comment]
Thank you. The corrections have been pushed.
