### ISSUE TITLE
Future Considerations for NENA Working Groups

### ISSUE THREAD

**Issue by tomneer** [NENA911/NG911GISDataModel#57]
**Purpose**
This issue is a parking lot for potential issues identified by the DS-Data Template Working Group to be considered in future versions of NENA documentation. 

**Considerations for NENA GIS Data Model v3**

- **Service URN** (ServiceURN) field length
  - The length of the Service URN field has been requested to be extended from 50 to 55 characters (#24) to support current Service URNs defined in RFC 5031 and NENA-STA-010.x. The DS-Data Template Working Group recommends extending the length of the Service URN field to 75 or 100 characters to future-proof the field from additional Service URNs that may be assigned. 
- **Elevation** (Elevation) field type
  - The Elevation field uses a data type of `INTEGER` which limits the positional accuracy of +/- 1-meter. The DS-Data Template Working Group recommends changing the Elevation data type from `INTEGER` to `FLOAT`. NENA-STA-006.2-2022 defines the Elevation values as "N" which is a non-negative integer values, changing to `FLOAT` which resolves elevations that may be negative.
- **StateOrEquivalentsA2** field length
  - The current length of the StateOrEquivalentA2 field is 2 characters which is sufficient for the US and Canadian values. [ISO 3166-2:MX](https://en.wikipedia.org/wiki/ISO_3166-2:MX) uses 3 characters. The DS-Data Template Working Group recommends extending the StateOrEquivalentA2 field from 2 to 3 characters to support Mexico.

**Comment by jasonhorning** [comment]
Researching the StateOrEquivalentsA2 issue... The only domain restriction I've found for this element is identified in CLDXF.  Has ISO3166-2 been recommended elsewhere?  

It may be worth suggesting that NENA documentation move to the ISO3166-2 standard completely, including for the US.

**Comment by tomneer** [comment]
Submitted as comment to [NENA-ADM-003_ISF_GIS_Data_Model_v3.docx](https://dev.nena.org/higherlogic/ws/groups/a7f0fdf5-1f14-4ef5-94f6-7227331fe593/documents/issues62/document?document_id=28187) on 2023-01-19.
