### ISSUE TITLE
State or Equivalent (A1)

### ISSUE THREAD

**Issue by dawnblanchard-DOIT** [NENA911/NG911GISDataModel#59]
The domain of value is restricted to 2, but when I create a point, I can only chose a state fully spelled out.

**Comment by tomneer** [comment]
The domain value of the State or Equivalent (A1) field is defined in [NENA-STA-006.2-2022](https://cdn.ymaws.com/www.nena.org/resource/resmgr/standards/nena-sta-006.2-2022_ng9-1-1_.pdf), **Section 5.107 State or Equivalent (A1)** explicitly as "represented by the two-letter UPPER CASE abbreviation". Extending the field length is not compliant with the NENA GIS Standard.

Nothing prevents you internally adjusting the field width, however, the transfer of data between organizations and to the Spatial Interface (SI) requires two characters.
