### ISSUE TITLE
Location Marker Indicator

### ISSUE THREAD

**Issue by dawnblanchard-DOIT** [NENA911/NG911GISDataModel#60]
The domain of value is restricted to 1, but when I create a point, I can only chose the fully spelled out word.

**Comment by tomneer** [comment]
The domain value of the Location Marker Indicator field is defined in [NENA-STA-006.2-2022](https://cdn.ymaws.com/www.nena.org/resource/resmgr/standards/nena-sta-006.2-2022_ng9-1-1_.pdf), **Section 5.59 Location Marker Indicator** explicitly as "P" or "L". Extending the field length is not compliant with the NENA GIS Standard.

Nothing prevents you internally adjusting the field width, however, the transfer of data between organizations and to the Spatial Interface (SI) requires one character.
