### ISSUE TITLE
Python 2.7 logic causing Python 3.x toolbox to fail.

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#63]
Hey Tom,

I got the following error message when attempting to create the Esri File GDB via ArcGIS Pro:
![image](https://user-images.githubusercontent.com/58236078/210440545-0e35dcf9-b05f-4cf9-88d0-eeea6f7054b8.png)

From what I've [researched](https://www.geeksforgeeks.org/difference-between-dict-items-and-dict-iteritems-in-python/), Python 3 doesn't support "iteritems" for dictionaries.

https://github.com/NENA911/NG911GISDataModel/blob/67a6aac3f91184f6c1492f8c97ea8a43f9bfa9e9/esri_geodatabase/NENA_NG911_Scripts/create_ng911_fgdb.py#L241-L247

-David L.

**Comment by tomneer** [comment]
Thanks. Thought I snuck around the differences in Python 2 and 3. Obviously not...

**Comment by jasonhorning** [comment]
If there isn’t a workaround to this, perhaps we should roll back.  It’s not ideal but I’d prefer to have a solution that works going forward as opposed to resolving an inconvenience on software with a declared end of life.Sent from my iPhoneOn Jan 3, 2023, at 3:19 PM, Tom Neer ***@***.***> wrote:﻿
Thanks. Thought I snuck around the differences in Python 2 and 3. Obviously not...

**Comment by NCT911-DLindsey** [comment]
Tom, I changed line 245 in my forked script from **domain["values"].iteritems()** to **domain["values"].items()** and so far it seems to be humming along nicely in Python 2.7 and Python 3 (at first glance). I'll deep dive it in the morning, but let me know if you see issues with that approach.

ArcMap:
![image](https://user-images.githubusercontent.com/58236078/210456519-f71b5a85-c761-4139-a67e-1af796e2ab83.png)

Pro:
![image](https://user-images.githubusercontent.com/58236078/210456395-cec53a7a-f51c-466a-8648-43ee07dcc5ec.png)

-David L.

**Comment by jasonhorning** [comment]
My test in in 10.5.1 this am is working and I have an ordered list of domain values from which to choose.
