### ISSUE TITLE
Agency table in Postgres is empty.

### ISSUE THREAD

**Issue by mapmanlynnwood** [NENA911/NG911GISDataModel#64]
Trying to populate any table isn't allowed without a DiscrpAgID or AgencyID.  I had to create my own to match the i3 definition of the AgencyID since the Agency table is empty.  I double checked the scripts to populate the domains and tables and its not there.

I used police.mpdc.dc.gov for both to populate the table.  Unfortunately I didn't get a screenshot.  But a missing agency id causes the agency_id_fkey and discrpagid_fkey constraints to yell.  The agency id in i3 says only approved agency id's can be used but I couldn't find the list of domain values.

Thanks
Matt Tenold

**Comment by jasonhorning** [comment]
Is this an issue still or can it be closed out?

**Comment by mapmanlynnwood** [comment]
I would call this closed.


[X]
Matt Tenold | GIS Administrator / FAA Certified Drone Pilot
Information Technology Department, City of Lynnwood
19100 44th Ave W, Lynnwood, WA 98036
Phone: (425) 670-5968
***@***.******@***.***>
www.lynnwoodwa.gov<http://www.lynnwoodwa.gov/>







[X]

On Jan 11, 2023, at 7:32 AM, jasonhorning ***@***.***> wrote:

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Is this an issue still or can it be closed out?

**Comment by jasonhorning** [comment]
OK, thanks Matt.  Just trying to tidy up before our call.
