### ISSUE TITLE
Esri schema description for 'Public' PlaceType is cut-off.

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#65]
Within the Esri schema_fgdb_v2.py file, line 225, there appears to be a cut off after 'public-transport', with 'ai" being the final letters. The postgresql template shows that a bit more should have been included.

https://github.com/NENA911/NG911GISDataModel/blob/6559a3e7d520076b06fea572b6896f7805f01820/esri_geodatabase/NENA_NG911_Scripts/schema/schema_fgdb_v2.py#L221-L225

![image](https://user-images.githubusercontent.com/58236078/211865586-37d9830b-facc-4cfc-a744-ffe6e5ada6a2.png)

-David L.

**Comment by tomneer** [comment]
Thanks David! Fixed.

**Comment by NCT911-DLindsey** [comment]
Hey Tom, sorry to nitpick, but it's suppose to be 'airport' not 'ai'.  (Although 'ai' seems to basically exist everywhere in public now. Ha.)

![image](https://user-images.githubusercontent.com/58236078/212167820-14eff9ed-36a8-4620-893b-1e94664947e2.png)

How the Postgresql schema reads:
![image](https://user-images.githubusercontent.com/58236078/212168053-ea18f20b-3d1c-42d8-b1a5-c65f7d857934.png)

**Comment by tomneer** [comment]
Oops. Fixed and updated. Thanks again for the catch!
