### ISSUE TITLE
Corrupted field spec for ServiceURN on FirePrivatePolygon, in schema_fgdb_v2.py

### ISSUE THREAD

**Issue by brudo** [NENA911/NG911GISDataModel#72]
The field specification for ServiceNum on FirePrivatePolygon contains an errant extra "" before the domain and default value. This may lead to the feature class being created with no domain on that field, and with a default value of "ServiceURN" instead of "urn:emergency:service:responder.fire.private".

This issue does not show up in the generated File Geodatabase, NG911_GIS_Template.gdb.zip appearing in Git, as it appears that only includes the primary feature classes, so it does not include FirePrivatePolygon.

**Comment by tomneer** [comment]
Thanks for the heads up. Will take a look. I would not be surprised to find another typo.
