### ISSUE TITLE
Question about Alias Field Name for CSite_Name field

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#73]
Hey Tom,

Regarding the Cell Sector layer's schema, is the Alias Field Name for CSite_Name supposed to be Cell Site ID? Or should it be Cell Site Name?

https://github.com/NENA911/NG911GISDataModel/blob/6e58e41331432799f783b30d523bbf438d1292a7/esri_geodatabase/NENA_NG911_Scripts/schema/schema_fgdb_v2.py#L2732

Site ID is already used with Site_ID, so I wanted to double check on that one as we build our new database. Thanks!

David

**Comment by tomneer** [comment]
David,

You are correct. This is a bug and needs to be fixed. It was not caught due to being an Alias which can be duplicated. Will correct as soon as possible.

-Tom
